name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        name: Create Release
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                include:
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-latest
                      platform: windows
                    - os: macos-latest
                      platform: macos

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"
                  cache-dependency-path: "package.json"

            - name: Install dependencies
              run: npm ci

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install Tauri CLI
              run: npm install -g @tauri-apps/cli

            - name: Build Tauri application
              run: npm run tauri build
              env:
                  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
                  TAURI_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

            - name: Upload release assets
              uses: actions/upload-artifact@v4
              with:
                  name: readnlearn-${{ matrix.platform }}-${{ github.ref_name }}
                  path: |
                      src-tauri/target/release/bundle/
                  retention-days: 90

    create-release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        needs: release

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Download all artifacts
              uses: actions/download-artifact@v4
              with:
                  path: ./artifacts

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      artifacts/readnlearn-linux-*/**/*
                      artifacts/readnlearn-windows-*/**/*
                      artifacts/readnlearn-macos-*/**/*
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
