name: Rust Security Audit

on:
    schedule:
        - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
    workflow_dispatch:

jobs:
    audit:
        name: Rust Security Audit
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Rust
              uses: dtolnay/rust-toolchain@stable

            - name: Install cargo-audit
              run: cargo install cargo-audit

            - name: Run cargo audit (sqlite-only; ignore MySQL advisory)
              run: cargo audit --ignore RUSTSEC-2023-0071
              working-directory: ./src-tauri
